spring.datasource.username=root
spring.datasource.password=MACos@#90
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

